# Generated by Django 5.0.4 on 2024-04-25 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_data_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 14, 35, 6, 90288)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='legenda',
            field=models.CharField(max_length=100),
        ),
    ]
